# Generated by Django 3.2.12 on 2022-09-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_postname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='postname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.post'),
        ),
    ]
