# Generated by Django 3.2.12 on 2022-09-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_likepost_postname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='postname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.post'),
        ),
    ]
