# Generated by Django 3.2.12 on 2022-09-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_likepost_postname'),
    ]

    operations = [
        migrations.CreateModel(
            name='commnetpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnent', models.TextField()),
                ('postname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
